// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import SparqlController from "./sparql_controller"
application.register("sparql", SparqlController)
